[package]
name = "rumba"
version = "0.0.1"
edition = "2021"

[lib]
path = "src/lib.rs"

[[bin]]
name = "rumba"
path = "src/main.rs"

[dependencies]
thiserror = "1.0"
anyhow = "1.0"

actix-web = "4"
actix-http = "3"
actix-rt = "2"
actix-identity = "0.4"
actix-session = { version = "0.6", features = ["cookie-session"] }
actix-web-httpauth = "0.6"

diesel = { version = "2.0.0-rc.0", features = ["postgres", "uuid", "r2d2", "chrono", "serde_json"] }
diesel_migrations = "2.0.0-rc.0"
diesel-derive-enum = { version = "2.0.0-rc.0", features = ["postgres"] }

elasticsearch = "7.14.0-alpha.1"

r2d2 = "0.8"

openidconnect = "2"
jsonwebtoken = "8"

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_with = { version = "1", features = ["base64"]}
serde_urlencoded = "0.7"
form_urlencoded = "1"
serde_path_to_error = "0.1"

config = "0.13"
hostname = "0.3"
slog = { version = "2.7", features = ["max_level_info", "release_max_level_info", "dynamic-keys"] }
slog-async = "2.6"
slog-envlogger = "2.2.0"
slog-mozlog-json = "0.1"
slog-scope = "4.4"
slog-stdlog = "4.1"
slog-term = "2.7"


uuid = { version = "1", features = ["serde", "v4", "fast-rng"] }
reqwest = { version = "0.11", features = ["blocking", "json"] }
chrono = "0.4"
url = "2"
base64 = "0.13"
futures-util = "0.3"
regex = "1.5"

const_format = "0.2"
once_cell = "1"

cadence = "0.29"
woothee = "0.13"
sentry = "0.31"
sentry-actix = "0.27"

[dev-dependencies]
stubr = "0.5.0-rc.1"
stubr-attributes = "0.5.0-rc.1"
assert-json-diff = "2.0.2"